apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  namespace: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express-pod
  template:
    metadata:
      labels:
        app: mongo-express-pod
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
             secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
             secretKeyRef:
                 name: mongodb-secret
                 key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
             configMapKeyRef:
                 name: mongo-express-configmap
                 key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: mongo-express
spec:
  selector:
    app: mongo-express-pod
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8081
      nodePort: 30110